stages:
  - tests
  - develop
  - master

flake8:
  stage: tests
  image: binkhq/python:3.8
  script:
    - pip install flake8
    - flake8

develop:
  stage: develop
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
  script:
    - export CTAG="develop-$(date +%F-%H%M%S)"
    - docker build --pull -t "$CI_REGISTRY/pyqa:$CTAG" .
    - docker push "$CI_REGISTRY/pyqa:$CTAG"
  only:
    - develop

master:
  stage: master
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
  script:
    - export CTAG="master-$(date +%F-%H%M%S)"
    - docker build --pull -t "$CI_REGISTRY/pyqa:$CTAG" .
    - docker push "$CI_REGISTRY/pyqa:$CTAG"
  only:
    - master
