stages:
  - tests
  - build

flake8:
  stage: tests
  image: binkhq/python:3.8
  script:
    - pip install flake8
    - flake8

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
  script:
    - docker build --pull -t "$CI_REGISTRY/pyqa:master-$CI_COMMIT_SHORT_SHA" .
    - docker push "$CI_REGISTRY/pyqa:master-$CI_COMMIT_SHORT_SHA"
  only:
    - master

